name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.4"
          - "9.10.1"
        exclude:
        # These don't work on GitHub CI anymore because they need llvm@13, which became
        # disabled on 12/31/2024
        - os: ubuntu-24.04-arm
          ghc: 8.10.7
        - os: ubuntu-24.04-arm
          ghc: 9.0.2

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell (Cabal)
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - name: Freeze
      run: |
        cabal update
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal freeze
        cat cabal.project.freeze

    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}-key1

    - name: Build
      run: cabal build all

    - name: Test
      run: cabal test

    - uses: actions/cache/save@v4
      if: always() && steps.cache-restore.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}-key1

  stack:
    name: ubuntu-latest / ${{ matrix.stack-yaml }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack-yaml:
        # - stack-ghc90.yaml
        - stack-ghc92.yaml
        - stack-ghc94.yaml
        - stack-ghc96.yaml
        - stack-ghc98.yaml
        - stack.yaml # Current dev version at ghc910

    steps:
    - uses: actions/checkout@v2

    - uses: haskell-actions/setup@v2
      name: Setup Haskell (Stack)
      with:
        enable-stack: true
        stack-no-global: true
        stack-version: "latest"

    - name: Run stack setup
      shell: bash
      run: |
        export STACK_EXTRA_ARGS="--stack-yaml ${{matrix.stack-yaml}}"
        stack setup $STACK_EXTRA_ARGS
        echo STACK_EXTRA_ARGS="$STACK_EXTRA_ARGS" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ matrix.stack-yaml }}-stack-key3

    - name: Build
      run: |
        stack build $STACK_EXTRA_ARGS --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test $STACK_EXTRA_ARGS
